
import "./globals.css";
import Layout from "@/component/Layout";
import { ShoppingCartItemProvider } from "@/context/ShoppingCartItem";
import { Lora } from "next/font/google";


const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-lora",
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lora.variable}>
      <body>
        <ShoppingCartItemProvider>
          <Layout>{children}</Layout> 
        </ShoppingCartItemProvider>
      </body>
    </html>
  );
}
